export const ADD_TODO_ITEM = 'ADD_TODO_ITEM';
export const MARK_SELECTED_TODO_ITEMS_DONE = 'MARK_SELECTED_TODO_ITEMS_DONE';
export const UNMARK_SELECTED_TODO_ITEMS_DONE = 'UNMARK_SELECTED_TODO_ITEMS_DONE';
export const GET_TODO_LIST = 'GET_TODO_LIST';
export const EDIT_TODO_ITEM = 'EDIT_TODO_ITEM';
export const DELETE_SELECTED_TODO_ITEMS = 'DELETE_SELECTED_TODO_ITEMS';
export const CLEAR_ALL = 'CLEAR_ALL';
